{
    'contributors': None,
    'truncated': False,
    'text': 'Shoutout to @OGDota2 , you guys are truly the inspiration to many of our players, we are looking forward to see you again in the next event.',
    'is_quote_status': False,
    'in_reply_to_status_id': None,
    'id': 849201805569343488,
    'favorite_count': 147,
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'retweeted': False,
    'coordinates': None,
    'entities': {
        'symbols': [],
        'user_mentions': [{
            'id': 3440528535,
            'indices': [12, 20],
            'id_str': '3440528535',
            'screen_name': 'OGDota2',
            'name': 'OG'
        }],
        'hashtags': [],
        'urls': []
    },
    'in_reply_to_screen_name': None,
    'in_reply_to_user_id': None,
    'retweet_count': 30,
    'id_str': '849201805569343488',
    'favorited': False,
    'user': {
        'follow_request_sent': False,
        'has_extended_profile': False,
        'profile_use_background_image': False,
        'default_profile_image': False,
        'id': 33230443,
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'verified': False,
        'translator_type': 'none',
        'profile_text_color': '000000',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/2582930654/mvxuu221v3w6vjuzgjvb_normal.jpeg',
        'profile_sidebar_fill_color': '000000',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/zD0mp5CchS',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.facebook.com/InvictusGaming.Official',
                    'display_url': 'facebook.com/InvictusGaming\u2026'
                }]
            },
            'description': {'urls': []}
        },
        'followers_count': 63553,
        'profile_sidebar_border_color': '000000',
        'id_str': '33230443',
        'profile_background_color': '000000',
        'listed_count': 376,
        'is_translation_enabled': False,
        'utc_offset': 28800,
        'statuses_count': 1502,
        'description': 'Invictus Gaming Official Twitter.Please follow here and on facebook.:)',
        'friends_count': 39,
        'location': 'Shanghai, China',
        'profile_link_color': '000000',
        'profile_image_url': 'http://pbs.twimg.com/profile_images/2582930654/mvxuu221v3w6vjuzgjvb_normal.jpeg',
        'following': True,
        'geo_enabled': False,
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'screen_name': 'invgaming',
        'lang': 'en',
        'profile_background_tile': False,
        'favourites_count': 36,
        'name': 'Invictus Gaming',
        'notifications': False,
        'url': 'http://t.co/zD0mp5CchS',
        'created_at': 'Sun Apr 19 15:49:25 +0000 2009',
        'contributors_enabled': False,
        'time_zone': 'Beijing',
        'protected': False,
        'default_profile': False,
        'is_translator': False
    },
    'geo': None,
    'in_reply_to_user_id_str': None,
    'lang': 'en',
    'created_at': 'Tue Apr 04 10:07:42 +0000 2017',
    'in_reply_to_status_id_str': None,
    'place': None
}