Status( #30(diff from json) #has-quoted_status #source & source_url #author is exactly the same as user
    contributors=None,
    truncated=True,
    text='Looking forward to representing @evl_uic at the Brazilian Symposium on Collaborative Systems:\u2026 https://t.co/0tnpyDj84W',
    is_quote_status=True,
    in_reply_to_status_id=None,
    id=877308619854934016,
    favorite_count=3,
    _api=<tweepy.api.API object at 0x10d148f90>,
    source='Twitter Web Client',
    quoted_status_id=868579630294413312,
    _json={ #28(diff from class) #has-quoted_status #source includes source and source_url #no-author
        'contributors': None,
        'truncated': True,
        'text': 'Looking forward to representing @evl_uic at the Brazilian Symposium on Collaborative Systems:\u2026 https://t.co/0tnpyDj84W',
        'is_quote_status': True,
        'in_reply_to_status_id': None,
        'id': 877308619854934016,
        'favorite_count': 3,
        'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        'quoted_status_id': 868579630294413312,
        'retweeted': False,
        'coordinates': None,
        'quoted_status': { #25(identical) #source includes source and source_url
            'contributors': None,
            'truncated': False,
            'text': 'Maxine Brown @evl_uic @cinegridbr will be a keynote speaker at the 14\xba Brazilian Symposium on Collaborative Systems: https://t.co/cvH6i5pgOd',
            'is_quote_status': False,
            'in_reply_to_status_id': None,
            'id': 868579630294413312,
            'favorite_count': 2,
            'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
            'retweeted': False,
            'coordinates': None,
            'entities': {
                'symbols': [],
                'user_mentions': [
                    {
                        'id': 314185571,
                        'indices': [13, 21],
                        'id_str': '314185571',
                        'screen_name': 'evl_uic',
                        'name': 'Electronic Vis. Lab'
                    },
                    {
                        'id': 2715769574,
                        'indices': [22, 33],
                        'id_str': '2715769574',
                        'screen_name': 'cinegridbr',
                        'name': 'CineGrid Brasil'
                    }
                ],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/cvH6i5pgOd',
                    'indices': [117, 140],
                    'expanded_url': 'http://csbc2017.mackenzie.br/eventos/14-sbsc',
                    'display_url': 'csbc2017.mackenzie.br/eventos/14-sbsc'
                }]
            },
            'in_reply_to_screen_name': None,
            'in_reply_to_user_id': None,
            'retweet_count': 0,
            'id_str': '868579630294413312',
            'favorited': False,
            'user': { #42(correct) #has-profile_banner_url #no-profile_location
                'follow_request_sent': False,
                'has_extended_profile': False,
                'profile_use_background_image': True,
                'default_profile_image': False,
                'id': 24748438,
                'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
                'verified': False,
                'translator_type': 'none',
                'profile_text_color': '333333',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
                'profile_sidebar_fill_color': 'DDFFCC',
                'entities': {
                    'url': {
                        'urls': [{
                            'url': 'http://t.co/mVshlT4rB6',
                            'indices': [0, 22],
                            'expanded_url': 'http://www.softwarestudies.com.br',
                            'display_url': 'softwarestudies.com.br'
                        }]
                    },
                    'description': {'urls': []}
                },
                'followers_count': 922,
                'profile_sidebar_border_color': 'BDDCAD',
                'id_str': '24748438',
                'profile_background_color': '9AE4E8',
                'listed_count': 60,
                'is_translation_enabled': False,
                'utc_offset': -10800,
                'statuses_count': 1125,
                'description': 'Software Studies Brazil @ Unifesp',
                'friends_count': 352,
                'location': 'S\xe3o Paulo, Brazil',
                'profile_link_color': '0084B4',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
                'following': False,
                'geo_enabled': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
                'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
                'screen_name': 'softwarestudies',
                'lang': 'en',
                'profile_background_tile': True,
                'favourites_count': 127,
                'name': 'Software Studies',
                'notifications': False,
                'url': 'http://t.co/mVshlT4rB6',
                'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
                'contributors_enabled': False,
                'time_zone': 'Brasilia',
                'protected': False,
                'default_profile': False,
                'is_translator': False
            },
            'geo': None,
            'in_reply_to_user_id_str': None,
            'possibly_sensitive': False,
            'possibly_sensitive_appealable': False,
            'lang': 'en',
            'created_at': 'Sat May 27 21:28:15 +0000 2017',
            'in_reply_to_status_id_str': None,
            'place': None
        },
        'entities': {
            'symbols': [],
            'user_mentions': [{
                'id': 314185571,
                'indices': [32, 40],
                'id_str': '314185571',
                'screen_name': 'evl_uic',
                'name': 'Electronic Vis. Lab'
            }],
            'hashtags': [],
            'urls': [{
                'url': 'https://t.co/0tnpyDj84W',
                'indices': [95, 118],
                'expanded_url': 'https://twitter.com/i/web/status/877308619854934016',
                'display_url': 'twitter.com/i/web/status/8\u2026'
            }]
        },
        'in_reply_to_screen_name': None,
        'in_reply_to_user_id': None,
        'retweet_count': 1,
        'id_str': '877308619854934016',
        'favorited': False,
        'user': {
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 314185571,
            'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': 'B8B8B8',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'profile_sidebar_fill_color': 'EFEFEF',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/wLvtCCBQjl',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.evl.uic.edu/index2.php',
                        'display_url': 'evl.uic.edu/index2.php'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 375,
            'profile_sidebar_border_color': 'EEEEEE',
            'id_str': '314185571',
            'profile_background_color': '131516',
            'listed_count': 30,
            'is_translation_enabled': False,
            'utc_offset': -18000,
            'statuses_count': 201,
            'description': 'The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
            'friends_count': 5,
            'location': 'Chicago, Il',
            'profile_link_color': 'B30000',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'following': True,
            'geo_enabled': False,
            'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
            'screen_name': 'evl_uic',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 2,
            'name': 'Electronic Vis. Lab',
            'notifications': False,
            'url': 'http://t.co/wLvtCCBQjl',
            'created_at': 'Thu Jun 09 21:07:18 +0000 2011',
            'contributors_enabled': False,
            'time_zone': 'Central Time (US & Canada)',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        'geo': None,
        'in_reply_to_user_id_str': None,
        'possibly_sensitive': False,
        'possibly_sensitive_appealable': False,
        'lang': 'en',
        'created_at': 'Tue Jun 20 23:34:09 +0000 2017',
        'quoted_status_id_str': '868579630294413312',
        'in_reply_to_status_id_str': None,
        'place': None
    },
    coordinates=None,
    quoted_status={ #25(identical) #source includes source and source_url
        'contributors': None,
        'truncated': False,
        'text': 'Maxine Brown @evl_uic @cinegridbr will be a keynote speaker at the 14\xba Brazilian Symposium on Collaborative Systems: https://t.co/cvH6i5pgOd',
        'is_quote_status': False,
        'in_reply_to_status_id': None,
        'id': 868579630294413312,
        'favorite_count': 2,
        'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        'retweeted': False,
        'coordinates': None,
        'entities': {
            'symbols': [],
            'user_mentions': [
                {
                    'id': 314185571,
                    'indices': [13, 21],
                    'id_str': '314185571',
                    'screen_name': 'evl_uic',
                    'name': 'Electronic Vis. Lab'
                },
                {
                    'id': 2715769574,
                    'indices': [22, 33],
                    'id_str': '2715769574',
                    'screen_name': 'cinegridbr',
                    'name': 'CineGrid Brasil'
                }
            ],
            'hashtags': [],
            'urls': [{
                'url': 'https://t.co/cvH6i5pgOd',
                'indices': [117, 140],
                'expanded_url': 'http://csbc2017.mackenzie.br/eventos/14-sbsc',
                'display_url': 'csbc2017.mackenzie.br/eventos/14-sbsc'
            }]
        },
        'in_reply_to_screen_name': None,
        'in_reply_to_user_id': None,
        'retweet_count': 0,
        'id_str': '868579630294413312',
        'favorited': False,
        'user': { #42(identical) #has-profile_banner_url #no-profile_location #no-status
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 24748438,
            'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': '333333',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'profile_sidebar_fill_color': 'DDFFCC',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/mVshlT4rB6',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.softwarestudies.com.br',
                        'display_url': 'softwarestudies.com.br'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 922,
            'profile_sidebar_border_color': 'BDDCAD',
            'id_str': '24748438',
            'profile_background_color': '9AE4E8',
            'listed_count': 60,
            'is_translation_enabled': False,
            'utc_offset': -10800,
            'statuses_count': 1125,
            'description': 'Software Studies Brazil @ Unifesp',
            'friends_count': 352,
            'location': 'S\xe3o Paulo, Brazil',
            'profile_link_color': '0084B4',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'following': False,
            'geo_enabled': False,
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
            'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'screen_name': 'softwarestudies',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 127,
            'name': 'Software Studies',
            'notifications': False,
            'url': 'http://t.co/mVshlT4rB6',
            'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
            'contributors_enabled': False,
            'time_zone': 'Brasilia',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        'geo': None,
        'in_reply_to_user_id_str': None,
        'possibly_sensitive': False,
        'possibly_sensitive_appealable': False,
        'lang': 'en',
        'created_at': 'Sat May 27 21:28:15 +0000 2017',
        'in_reply_to_status_id_str': None,
        'place': None
    },
    entities={
        'symbols': [],
        'user_mentions': [{
            'id': 314185571,
            'indices': [32, 40],
            'id_str': '314185571',
            'screen_name': 'evl_uic',
            'name': 'Electronic Vis. Lab'
        }],
        'hashtags': [],
        'urls': [{
            'url': 'https://t.co/0tnpyDj84W',
            'indices': [95, 118],
            'expanded_url': 'https://twitter.com/i/web/status/877308619854934016',
            'display_url': 'twitter.com/i/web/status/8\u2026'
        }]
    },
    in_reply_to_screen_name=None,
    id_str='877308619854934016',
    retweet_count=1,
    in_reply_to_user_id=None,
    favorited=False,
    source_url='http://twitter.com',
    user=User( #41
        follow_request_sent=False,
        has_extended_profile=False,
        profile_use_background_image=True,
        _json={ #41
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 314185571,
            'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': 'B8B8B8',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'profile_sidebar_fill_color': 'EFEFEF',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/wLvtCCBQjl',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.evl.uic.edu/index2.php',
                        'display_url': 'evl.uic.edu/index2.php'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 375,
            'profile_sidebar_border_color': 'EEEEEE',
            'id_str': '314185571',
            'profile_background_color': '131516',
            'listed_count': 30,
            'is_translation_enabled': False,
            'utc_offset': -18000,
            'statuses_count': 201,
            'description': 'The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
            'friends_count': 5,
            'location': 'Chicago, Il',
            'profile_link_color': 'B30000',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'following': True,
            'geo_enabled': False,
            'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
            'screen_name': 'evl_uic',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 2,
            'name': 'Electronic Vis. Lab',
            'notifications': False,
            'url': 'http://t.co/wLvtCCBQjl',
            'created_at': 'Thu Jun 09 21:07:18 +0000 2011',
            'contributors_enabled': False,
            'time_zone': 'Central Time (US & Canada)',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        time_zone='Central Time (US & Canada)',
        id=314185571,
        description='The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
        _api=<tweepy.api.API object at 0x10d148f90>,
        verified=False,
        profile_text_color='B8B8B8',
        profile_image_url_https='https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        profile_sidebar_fill_color='EFEFEF',
        is_translator=False,
        geo_enabled=False,
        entities={
            'url': {
                'urls': [{
                    'url': 'http://t.co/wLvtCCBQjl',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.evl.uic.edu/index2.php',
                    'display_url': 'evl.uic.edu/index2.php'
                }]
            },
            'description': {'urls': []}
        },
        followers_count=375,
        protected=False,
        id_str='314185571',
        default_profile_image=False,
        listed_count=30,
        lang='en',
        utc_offset=-18000,
        statuses_count=201,
        profile_background_color='131516',
        friends_count=5,
        profile_link_color='B30000',
        profile_image_url='http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        notifications=False,
        default_profile=False,
        profile_background_image_url_https='https://abs.twimg.com/images/themes/theme14/bg.gif',
        profile_background_image_url='http://abs.twimg.com/images/themes/theme14/bg.gif',
        name='Electronic Vis. Lab',
        is_translation_enabled=False,
        profile_background_tile=True,
        favourites_count=2,
        screen_name='evl_uic',
        url='http://t.co/wLvtCCBQjl',
        created_at=datetime.datetime(2011, 6, 9, 21, 7, 18),
        contributors_enabled=False,
        location='Chicago, Il',
        profile_sidebar_border_color='EEEEEE',
        translator_type='none',
        following=True
    ),
    geo=None,
    in_reply_to_user_id_str=None,
    possibly_sensitive=False,
    possibly_sensitive_appealable=False,
    lang='en',
    created_at=datetime.datetime(2017, 6, 20, 23, 34, 9),
    author=User(
        follow_request_sent=False,
        has_extended_profile=False,
        profile_use_background_image=True,
        _json={
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 314185571,
            'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': 'B8B8B8',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'profile_sidebar_fill_color': 'EFEFEF',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/wLvtCCBQjl',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.evl.uic.edu/index2.php',
                        'display_url': 'evl.uic.edu/index2.php'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 375,
            'profile_sidebar_border_color': 'EEEEEE',
            'id_str': '314185571',
            'profile_background_color': '131516',
            'listed_count': 30,
            'is_translation_enabled': False,
            'utc_offset': -18000,
            'statuses_count': 201,
            'description': 'The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
            'friends_count': 5,
            'location': 'Chicago, Il',
            'profile_link_color': 'B30000',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
            'following': True,
            'geo_enabled': False,
            'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
            'screen_name': 'evl_uic',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 2,
            'name': 'Electronic Vis. Lab',
            'notifications': False,
            'url': 'http://t.co/wLvtCCBQjl',
            'created_at': 'Thu Jun 09 21:07:18 +0000 2011',
            'contributors_enabled': False,
            'time_zone': 'Central Time (US & Canada)',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        time_zone='Central Time (US & Canada)',
        id=314185571,
        description='The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
        _api=<tweepy.api.API object at 0x10d148f90>,
        verified=False,
        profile_text_color='B8B8B8',
        profile_image_url_https='https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        profile_sidebar_fill_color='EFEFEF',
        is_translator=False,
        geo_enabled=False,
        entities={
            'url': {
                'urls': [{
                    'url': 'http://t.co/wLvtCCBQjl',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.evl.uic.edu/index2.php',
                    'display_url': 'evl.uic.edu/index2.php'
                }]
            },
            'description': {'urls': []}
        },
        followers_count=375,
        protected=False,
        id_str='314185571',
        default_profile_image=False,
        listed_count=30,
        lang='en',
        utc_offset=-18000,
        statuses_count=201,
        profile_background_color='131516',
        friends_count=5,
        profile_link_color='B30000',
        profile_image_url='http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        notifications=False,
        default_profile=False,
        profile_background_image_url_https='https://abs.twimg.com/images/themes/theme14/bg.gif',
        profile_background_image_url='http://abs.twimg.com/images/themes/theme14/bg.gif',
        name='Electronic Vis. Lab',
        is_translation_enabled=False,
        profile_background_tile=True,
        favourites_count=2,
        screen_name='evl_uic',
        url='http://t.co/wLvtCCBQjl',
        created_at=datetime.datetime(2011, 6, 9, 21, 7, 18),
        contributors_enabled=False,
        location='Chicago, Il',
        profile_sidebar_border_color='EEEEEE',
        translator_type='none',
        following=True
    ),
    quoted_status_id_str='868579630294413312',
    in_reply_to_status_id_str=None,
    place=None,
    retweeted=False
)