{
    'contributors': None,
    'truncated': False,
    'text': '@invgaming Tell those kids to stop betting and just enjoy the games.',
    'is_quote_status': False,
    'in_reply_to_status_id': 865264405235154944,
    'id': 865375128871424000,
    'favorite_count': 1,
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'retweeted': False,
    'coordinates': None,
    'entities': {'symbols': [],
    'user_mentions': [{'id': 33230443,
    'indices': [0, 10],
    'id_str': '33230443',
    'screen_name': 'invgaming',
    'name': 'Invictus Gaming'}],
    'hashtags': [],
    'urls': []},
    'in_reply_to_screen_name': 'invgaming',
    'in_reply_to_user_id': 33230443,
    'retweet_count': 0,
    'id_str': '865375128871424000',
    'favorited': False,
    'user': {'follow_request_sent': False,
    'has_extended_profile': False,
    'profile_use_background_image': False,
    'default_profile_image': False,
    'id': 104091062,
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'verified': False,
    'translator_type': 'none',
    'profile_text_color': '000000',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/817062592/______normal.jpg',
    'profile_sidebar_fill_color': '000000',
    'entities': {'url': {'urls': [{'url': 'https://t.co/9KeLXabTlg',
    'indices': [0, 23],
    'expanded_url': 'http://joysword.com',
    'display_url': 'joysword.com'}]},
    'description': {'urls': []}},
    'followers_count': 18,
    'profile_sidebar_border_color': '000000',
    'id_str': '104091062',
    'profile_background_color': '000000',
    'listed_count': 0,
    'is_translation_enabled': False,
    'utc_offset': -18000,
    'statuses_count': 55,
    'description': 'I live to serve all believers',
    'friends_count': 54,
    'location': 'Chicago, IL',
    'profile_link_color': '0084B4',
    'profile_image_url': 'http://pbs.twimg.com/profile_images/817062592/______normal.jpg',
    'following': False,
    'geo_enabled': True,
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'screen_name': 'joyswordy',
    'lang': 'en',
    'profile_background_tile': False,
    'favourites_count': 2,
    'name': 'joysword',
    'notifications': False,
    'url': 'https://t.co/9KeLXabTlg',
    'created_at': 'Tue Jan 12 06:37:54 +0000 2010',
    'contributors_enabled': False,
    'time_zone': 'Central Time (US & Canada)',
    'protected': False,
    'default_profile': False,
    'is_translator': False}, u'geo': None, u'in_reply_to_user_id_str': '33230443', u'lang': 'en', u'created_at': 'Fri May 19 01:14:43 +0000 2017', u'in_reply_to_status_id_str': '865264405235154944', u'place': None}