User( #44
    follow_request_sent=False,
    has_extended_profile=False,
    profile_use_background_image=True,
    _json={ #44
        'follow_request_sent': False,
        'has_extended_profile': False,
        'profile_use_background_image': True,
        'profile_text_color': '333333',
        'default_profile_image': False,
        'id': 24748438,
        'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        'verified': False,
        'translator_type': 'none',
        'profile_location': None,
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        'profile_sidebar_fill_color': 'DDFFCC',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/mVshlT4rB6',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.softwarestudies.com.br',
                    'display_url': 'softwarestudies.com.br'
                }]
            },
            'description': {'urls': []}
        },
        'followers_count': 922,
        'profile_sidebar_border_color': 'BDDCAD',
        'id_str': '24748438',
        'profile_background_color': '9AE4E8',
        'listed_count': 60,
        'status': { #25
            'contributors': None,
            'truncated': False,
            'text': 'RT @manovich: The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
            'is_quote_status': False,
            'in_reply_to_status_id': None,
            'id': 885572331384573953,
            'favorite_count': 0,
            'source': '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Lite</a>',
            'retweeted': False,
            'coordinates': None,
            'entities': {
                'symbols': [],
                'user_mentions': [{'id': 13257922,
                'indices': [3, 12],
                'id_str': '13257922',
                'screen_name': 'manovich',
                'name': 'manovich'}],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/6fQ9RaXuPw',
                    'indices': [68, 91],
                    'expanded_url': 'http://bit.ly/2sbkGvK',
                    'display_url': 'bit.ly/2sbkGvK'
                }],
                'media': [{
                    'source_user_id': 13257922,
                    'source_status_id_str': '882818947405447168',
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'source_user_id_str': '13257922',
                    'source_status_id': 882818947405447168,
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354,
                            'resize': 'fit',
                            'w': 680},
                        'large': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'medium': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'thumb': {'h': 150,
                            'resize': 'crop',
                            'w': 150}
                    },
                    'indices': [92, 115],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            },
            'in_reply_to_screen_name': None,
            'in_reply_to_user_id': None,
            'retweet_count': 14,
            'id_str': '885572331384573953',
            'favorited': False,
            'retweeted_status': { #24
                'contributors': None,
                'truncated': False,
                'text': 'The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
                'is_quote_status': False,
                'in_reply_to_status_id': None,
                'id': 882818947405447168,
                'favorite_count': 20,
                'source': '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
                'retweeted': False,
                'coordinates': None,
                'entities': {
                    'symbols': [],
                    'user_mentions': [],
                    'hashtags': [],
                    'urls': [{
                        'url': 'https://t.co/6fQ9RaXuPw',
                        'indices': [54, 77],
                        'expanded_url': 'http://bit.ly/2sbkGvK',
                        'display_url': 'bit.ly/2sbkGvK'
                    }],
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {
                                'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                },
                'in_reply_to_screen_name': None,
                'in_reply_to_user_id': None,
                'retweet_count': 14,
                'id_str': '882818947405447168',
                'favorited': False,
                'geo': None,
                'in_reply_to_user_id_str': None,
                'possibly_sensitive': False,
                'lang': 'en',
                'created_at': 'Thu Jul 06 04:30:13 +0000 2017',
                'in_reply_to_status_id_str': None,
                'place': None,
                'extended_entities': {
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                }
            },
            'geo': None,
            'in_reply_to_user_id_str': None,
            'possibly_sensitive': False,
            'lang': 'en',
            'created_at': 'Thu Jul 13 18:51:11 +0000 2017',
            'in_reply_to_status_id_str': None,
            'place': None,
            'extended_entities': {
                'media': [{
                    'source_user_id': 13257922,
                    'source_status_id_str': '882818947405447168',
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'source_user_id_str': '13257922',
                    'source_status_id': 882818947405447168,
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354,
                            'resize': 'fit',
                            'w': 680},
                        'large': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'medium': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'thumb': {'h': 150,
                            'resize': 'crop',
                            'w': 150}
                    },
                    'indices': [92, 115],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            }
        },
        'is_translation_enabled': False,
        'utc_offset': -10800,
        'statuses_count': 1125,
        'description': 'Software Studies Brazil @ Unifesp',
        'friends_count': 352,
        'location': 'S\xe3o Paulo, Brazil',
        'profile_link_color': '0084B4',
        'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        'following': False,
        'geo_enabled': False,
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
        'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        'name': 'Software Studies',
        'lang': 'en',
        'profile_background_tile': True,
        'favourites_count': 127,
        'screen_name': 'softwarestudies',
        'notifications': False,
        'url': 'http://t.co/mVshlT4rB6',
        'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
        'contributors_enabled': False,
        'time_zone': 'Brasilia',
        'protected': False,
        'default_profile': False,
        'is_translator': False
    },
    time_zone='Brasilia',
    id=24748438,
    description='Software Studies Brazil @ Unifesp',
    _api=<tweepy.api.API object at 0x10cafff90>,
    verified=False,
    profile_location=None,
    profile_image_url_https='https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
    profile_sidebar_fill_color='DDFFCC',
    is_translator=False,
    geo_enabled=False,
    entities={
        'url': {
            'urls': [{
                'url': 'http://t.co/mVshlT4rB6',
                'indices': [0, 22],
                'expanded_url': 'http://www.softwarestudies.com.br',
                'display_url': 'softwarestudies.com.br'
            }]
        },
        'description': {'urls': []}
    },
    followers_count=922,
    protected=False,
    id_str='24748438',
    default_profile_image=False,
    listed_count=60,
    status=Status( #26 #source & source_url
        contributors=None,
        truncated=False,
        text='RT @manovich: The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
        is_quote_status=False,
        in_reply_to_status_id=None,
        id=885572331384573953,
        favorite_count=0,
        _api=<tweepy.api.API object at 0x10cafff90>,
        source='Twitter Lite',
        _json={ #25 #source includes source & source_url
            'contributors': None,
            'truncated': False,
            'text': 'RT @manovich: The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
            'is_quote_status': False,
            'in_reply_to_status_id': None,
            'id': 885572331384573953,
            'favorite_count': 0,
            'source': '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Lite</a>',
            'retweeted': False,
            'coordinates': None,
            'entities': {
                'symbols': [],
                'user_mentions': [{
                    'id': 13257922,
                    'indices': [3, 12],
                    'id_str': '13257922',
                    'screen_name': 'manovich',
                    'name': 'manovich'
                }],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/6fQ9RaXuPw',
                    'indices': [68, 91],
                    'expanded_url': 'http://bit.ly/2sbkGvK',
                    'display_url': 'bit.ly/2sbkGvK'
                }],
                'media': [{
                    'source_user_id': 13257922,
                    'source_status_id_str': '882818947405447168',
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'source_user_id_str': '13257922',
                    'source_status_id': 882818947405447168,
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354,
                            'resize': 'fit',
                            'w': 680},
                        'large': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'medium': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'thumb': {'h': 150,
                            'resize': 'crop',
                            'w': 150}
                    },
                    'indices': [92, 115],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            },
            'in_reply_to_screen_name': None,
            'in_reply_to_user_id': None,
            'retweet_count': 14,
            'id_str': '885572331384573953',
            'favorited': False,
            'retweeted_status': { #24
                'contributors': None,
                'truncated': False,
                'text': 'The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
                'is_quote_status': False,
                'in_reply_to_status_id': None,
                'id': 882818947405447168,
                'favorite_count': 20,
                'source': '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
                'retweeted': False,
                'coordinates': None,
                'entities': {
                    'symbols': [],
                    'user_mentions': [],
                    'hashtags': [],
                    'urls': [{
                        'url': 'https://t.co/6fQ9RaXuPw',
                        'indices': [54, 77],
                        'expanded_url': 'http://bit.ly/2sbkGvK',
                        'display_url': 'bit.ly/2sbkGvK'
                    }],
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                },
                'in_reply_to_screen_name': None,
                'in_reply_to_user_id': None,
                'retweet_count': 14,
                'id_str': '882818947405447168',
                'favorited': False,
                'geo': None,
                'in_reply_to_user_id_str': None,
                'possibly_sensitive': False,
                'lang': 'en',
                'created_at': 'Thu Jul 06 04:30:13 +0000 2017',
                'in_reply_to_status_id_str': None,
                'place': None,
                'extended_entities': {
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                }
            },
            'geo': None,
            'in_reply_to_user_id_str': None,
            'possibly_sensitive': False,
            'lang': 'en',
            'created_at': 'Thu Jul 13 18:51:11 +0000 2017',
            'in_reply_to_status_id_str': None,
            'place': None,
            'extended_entities': {
                'media': [{
                    'source_user_id': 13257922,
                    'source_status_id_str': '882818947405447168',
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'source_user_id_str': '13257922',
                    'source_status_id': 882818947405447168,
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354,
                            'resize': 'fit',
                            'w': 680},
                        'large': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'medium': {'h': 500,
                            'resize': 'fit',
                            'w': 960},
                        'thumb': {'h': 150,
                            'resize': 'crop',
                            'w': 150}
                    },
                    'indices': [92, 115],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            }
        },
        coordinates=None,
        entities={
            'symbols': [],
            'user_mentions': [{
                'id': 13257922,
                'indices': [3, 12],
                'id_str': '13257922',
                'screen_name': 'manovich',
                'name': 'manovich'
            }],
            'hashtags': [],
            'urls': [{
                'url': 'https://t.co/6fQ9RaXuPw',
                'indices': [68, 91],
                'expanded_url': 'http://bit.ly/2sbkGvK',
                'display_url': 'bit.ly/2sbkGvK'
            }],
            'media': [{
                'source_user_id': 13257922,
                'source_status_id_str': '882818947405447168',
                'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                'display_url': 'pic.twitter.com/bidRJm1BZq',
                'url': 'https://t.co/bidRJm1BZq',
                'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                'source_user_id_str': '13257922',
                'source_status_id': 882818947405447168,
                'id_str': '882818945258070018',
                'sizes': {
                    'small': {
                        'h': 354,
                        'resize': 'fit',
                        'w': 680
                    },
                    'large': {
                        'h': 500,
                        'resize': 'fit',
                        'w': 960
                    },
                    'medium': {
                        'h': 500,
                        'resize': 'fit',
                        'w': 960
                    },
                    'thumb': {
                        'h': 150,
                        'resize': 'crop',
                        'w': 150
                    }
                },
                'indices': [92, 115],
                'type': 'photo',
                'id': 882818945258070018,
                'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
            }]
        },
        in_reply_to_screen_name=None,
        id_str='885572331384573953',
        retweet_count=14,
        in_reply_to_user_id=None,
        favorited=False,
        retweeted_status=Status( #25
            contributors=None,
            truncated=False,
            text='The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
            is_quote_status=False,
            in_reply_to_status_id=None,
            id=882818947405447168,
            favorite_count=20,
            _api=<tweepy.api.API object at 0x10cafff90>,
            source='Buffer',
            _json={ #24
                'contributors': None,
                'truncated': False,
                'text': 'The Museum of Capitalism opened in Oakland this June. https://t.co/6fQ9RaXuPw https://t.co/bidRJm1BZq',
                'is_quote_status': False,
                'in_reply_to_status_id': None,
                'id': 882818947405447168,
                'favorite_count': 20,
                'source': '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
                'retweeted': False,
                'coordinates': None,
                'entities': {
                    'symbols': [],
                    'user_mentions': [],
                    'hashtags': [],
                    'urls': [{
                        'url': 'https://t.co/6fQ9RaXuPw',
                        'indices': [54, 77],
                        'expanded_url': 'http://bit.ly/2sbkGvK',
                        'display_url': 'bit.ly/2sbkGvK'
                    }],
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                },
                'in_reply_to_screen_name': None,
                'in_reply_to_user_id': None,
                'retweet_count': 14,
                'id_str': '882818947405447168',
                'favorited': False,
                'geo': None,
                'in_reply_to_user_id_str': None,
                'possibly_sensitive': False,
                'lang': 'en',
                'created_at': 'Thu Jul 06 04:30:13 +0000 2017',
                'in_reply_to_status_id_str': None,
                'place': None,
                'extended_entities': {
                    'media': [{
                        'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                        'display_url': 'pic.twitter.com/bidRJm1BZq',
                        'url': 'https://t.co/bidRJm1BZq',
                        'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                        'id_str': '882818945258070018',
                        'sizes': {
                            'small': {'h': 354,
                                'resize': 'fit',
                                'w': 680},
                            'large': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'medium': {'h': 500,
                                'resize': 'fit',
                                'w': 960},
                            'thumb': {'h': 150,
                                'resize': 'crop',
                                'w': 150}
                        },
                        'indices': [78, 101],
                        'type': 'photo',
                        'id': 882818945258070018,
                        'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                    }]
                }
            },
            coordinates=None,
            entities={
                'symbols': [],
                'user_mentions': [],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/6fQ9RaXuPw',
                    'indices': [54, 77],
                    'expanded_url': 'http://bit.ly/2sbkGvK',
                    'display_url': 'bit.ly/2sbkGvK'
                }],
                'media': [{
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354, 'resize': 'fit', 'w': 680},
                        'large': {'h': 500, 'resize': 'fit', 'w': 960},
                        'medium': {'h': 500, 'resize': 'fit', 'w': 960},
                        'thumb': {'h': 150, 'resize': 'crop', 'w': 150}
                    },
                    'indices': [78,101],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            },
            in_reply_to_screen_name=None,
            id_str='882818947405447168',
            retweet_count=14,
            in_reply_to_user_id=None,
            favorited=False,
            source_url='http://bufferapp.com',
            geo=None,
            in_reply_to_user_id_str=None,
            possibly_sensitive=False,
            lang='en',
            created_at=datetime.datetime(2017, 7, 6, 4, 30, 13),
            in_reply_to_status_id_str=None,
            place=None,
            extended_entities={
                'media': [{
                    'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                    'display_url': 'pic.twitter.com/bidRJm1BZq',
                    'url': 'https://t.co/bidRJm1BZq',
                    'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                    'id_str': '882818945258070018',
                    'sizes': {
                        'small': {'h': 354, 'resize': 'fit', 'w': 680 },
                        'large': {'h': 500, 'resize': 'fit', 'w': 960},
                        'medium': {'h': 500, 'resize': 'fit', 'w': 960},
                        'thumb': {'h': 150, 'resize': 'crop', 'w': 150}
                    },
                    'indices': [78, 101],
                    'type': 'photo',
                    'id': 882818945258070018,
                    'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
                }]
            },
            retweeted=False
        ),
        source_url='https://mobile.twitter.com',
        geo=None,
        in_reply_to_user_id_str=None,
        possibly_sensitive=False,
        lang='en',
        created_at=datetime.datetime(2017, 7, 13, 18, 51, 11),
        in_reply_to_status_id_str=None,
        place=None,
        extended_entities={
            'media': [{
                'source_user_id': 13257922,
                'source_status_id_str': '882818947405447168',
                'expanded_url': 'https://twitter.com/manovich/status/882818947405447168/photo/1',
                'display_url': 'pic.twitter.com/bidRJm1BZq',
                'url': 'https://t.co/bidRJm1BZq',
                'media_url_https': 'https://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg',
                'source_user_id_str': '13257922',
                'source_status_id': 882818947405447168,
                'id_str': '882818945258070018',
                'sizes': {
                    'small': {'h': 354,
                        'resize': 'fit',
                        'w': 680},
                    'large': {'h': 500,
                        'resize': 'fit',
                        'w': 960},
                    'medium': {'h': 500,
                        'resize': 'fit',
                        'w': 960},
                    'thumb': {'h': 150,
                        'resize': 'crop',
                        'w': 150}
                },
                'indices': [92, 115],
                'type': 'photo',
                'id': 882818945258070018,
                'media_url': 'http://pbs.twimg.com/media/DEBnJ0EXoAImJ1j.jpg'
            }]
        },
        retweeted=False
    ),
    lang='en',
    utc_offset=-10800,
    statuses_count=1125,
    profile_background_color='9AE4E8',
    friends_count=352,
    profile_link_color='0084B4',
    profile_image_url='http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
    notifications=False,
    default_profile=False,
    favourites_count=127,
    profile_background_image_url_https='https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
    profile_banner_url='https://pbs.twimg.com/profile_banners/24748438/1400118299',
    profile_background_image_url='http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
    screen_name='softwarestudies',
    is_translation_enabled=False,
    profile_background_tile=True,
    profile_text_color='333333',
    name='Software Studies',
    url='http://t.co/mVshlT4rB6',
    created_at=datetime.datetime(2009, 3, 16, 19, 15, 13),
    contributors_enabled=False,
    location='S\xe3o Paulo, Brazil',
    profile_sidebar_border_color='BDDCAD',
    translator_type='none',
    following=False
)