{
    'contributors': None,
    'truncated': False,
    'text': "RT @WojVerticalNBA: Sources: Cleveland owner Dan Gilbert is targeting Chauncey Billups to become Cavs' top basketball executive. Sides expe\u2026",
    'is_quote_status': False,
    'in_reply_to_status_id': None,
    'id': 876977229640724480,
    'favorite_count': 0,
    'source': '<a href="http://place.holder" rel="nofollow">query tool</a>',
    'retweeted': True,
    'coordinates': None,
    'entities': {
        'symbols': [],
        'user_mentions': [{
            'id': 50323173,
            'indices': [3, 18],
            'id_str': '50323173',
            'screen_name': 'WojVerticalNBA',
            'name': 'Adrian Wojnarowski'
        }],
        'hashtags': [],
        'urls': []
    },
    'in_reply_to_screen_name': None,
    'in_reply_to_user_id': None,
    'retweet_count': 1105,
    'id_str': '876977229640724480',
    'favorited': False,
    'retweeted_status': {
        'contributors': None,
        'truncated': False,
        'text': "Sources: Cleveland owner Dan Gilbert is targeting Chauncey Billups to become Cavs' top basketball executive. Sides expected to talk soon.",
        'is_quote_status': False,
        'in_reply_to_status_id': None,
        'id': 876953479302057984,
        'favorite_count': 1467,
        'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        'retweeted': True,
        'coordinates': None,
        'entities': {
            'symbols': [],
            'user_mentions': [],
            'hashtags': [],
            'urls': []
        },
        'in_reply_to_screen_name': None,
        'in_reply_to_user_id': None,
        'retweet_count': 1105,
        'id_str': '876953479302057984',
        'favorited': False,
        'user': {
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 50323173,
            'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/679082751690039297/ArImomTA.jpg',
            'verified': True,
            'translator_type': 'none',
            'profile_text_color': '333333',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/840373625979052033/8pXI1-F9_normal.jpg',
            'profile_sidebar_fill_color': 'DDFFCC',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'https://t.co/TOcy3LCy8Z',
                        'indices': [0, 23],
                        'expanded_url': 'https://www.facebook.com/TheVerticalWoj/',
                        'display_url': 'facebook.com/TheVerticalWoj/'
                    }]
                },
                'description': {
                    'urls': [{
                        'url': 'https://t.co/rehyhg7Z4X',
                        'indices': [10, 33],
                        'expanded_url': 'http://TheVertical.com',
                        'display_url': 'TheVertical.com'
                    }]
                }
            },
            'followers_count': 1727557,
            'profile_sidebar_border_color': 'FFFFFF',
            'id_str': '50323173',
            'profile_background_color': '642D8B',
            'listed_count': 21415,
            'is_translation_enabled': False,
            'utc_offset': -14400,
            'statuses_count': 12472,
            'description': 'Editor of https://t.co/rehyhg7Z4X: Web hub of NBA news, information and storytelling on Yahoo. Host of @TheVertical Podcast with Woj.',
            'friends_count': 632,
            'location': 'New York, NY',
            'profile_link_color': 'FF0000',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/840373625979052033/8pXI1-F9_normal.jpg',
            'following': True,
            'geo_enabled': True,
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/50323173/1489428127',
            'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/679082751690039297/ArImomTA.jpg',
            'screen_name': 'WojVerticalNBA',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 3507,
            'name': 'Adrian Wojnarowski',
            'notifications': False,
            'url': 'https://t.co/TOcy3LCy8Z',
            'created_at': 'Wed Jun 24 14:43:40 +0000 2009',
            'contributors_enabled': False,
            'time_zone': 'Eastern Time (US & Canada)',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        'geo': None,
        'in_reply_to_user_id_str': None,
        'lang': 'en',
        'created_at': 'Tue Jun 20 00:02:57 +0000 2017',
        'in_reply_to_status_id_str': None,
        'place': None
    },
    'user': {
        'follow_request_sent': False,
        'has_extended_profile': False,
        'profile_use_background_image': False,
        'default_profile_image': False,
        'id': 104091062,
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'verified': False,
        'translator_type': 'none',
        'profile_text_color': '000000',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/817062592/______normal.jpg',
        'profile_sidebar_fill_color': '000000',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'https://t.co/9KeLXabTlg',
                    'indices': [0, 23],
                    'expanded_url': 'http://joysword.com',
                    'display_url': 'joysword.com'
                }]
            },
            'description': { 'urls': [] }
        },
        'followers_count': 18,
        'profile_sidebar_border_color': '000000',
        'id_str': '104091062',
        'profile_background_color': '000000',
        'listed_count': 0,
        'is_translation_enabled': False,
        'utc_offset': -18000,
        'statuses_count': 55,
        'description': 'I live to serve all believers',
        'friends_count': 54,
        'location': 'Chicago, IL',
        'profile_link_color': '0084B4',
        'profile_image_url': 'http://pbs.twimg.com/profile_images/817062592/______normal.jpg',
        'following': False,
        'geo_enabled': True,
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'screen_name': 'joyswordy',
        'lang': 'en',
        'profile_background_tile': False,
        'favourites_count': 2,
        'name': 'joysword',
        'notifications': False,
        'url': 'https://t.co/9KeLXabTlg',
        'created_at': 'Tue Jan 12 06:37:54 +0000 2010',
        'contributors_enabled': False,
        'time_zone': 'Central Time (US & Canada)',
        'protected': False,
        'default_profile': False,
        'is_translator': False
    },
    'geo': None,
    'in_reply_to_user_id_str': None,
    'lang': 'en',
    'created_at': 'Tue Jun 20 01:37:19 +0000 2017',
    'in_reply_to_status_id_str': None,
    'place': None
}
