User( #43 #no-profile_banner_url
    follow_request_sent=False,
    has_extended_profile=False,
    profile_use_background_image=True,
    _json={ #43 #no-profile_banner_url
        'follow_request_sent': False,
        'has_extended_profile': False,
        'profile_use_background_image': True,
        'profile_text_color': 'B8B8B8',
        'default_profile_image': False,
        'id': 314185571,
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
        'verified': False,
        'translator_type': 'none',
        'profile_location': None,
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        'profile_sidebar_fill_color': 'EFEFEF',
        'entities': {
            'url': {
                'urls': [{
                    'url': 'http://t.co/wLvtCCBQjl',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.evl.uic.edu/index2.php',
                    'display_url': 'evl.uic.edu/index2.php'
                }]
            },
            'description': {'urls': []}
        },
        'followers_count': 375,
        'profile_sidebar_border_color': 'EEEEEE',
        'id_str': '314185571',
        'profile_background_color': '131516',
        'listed_count': 30,
        'status': { #25 #source includes source & source url
            'contributors': None,
            'truncated': True,
            'text': 'Looking forward to representing @evl_uic at the Brazilian Symposium on Collaborative Systems:\u2026 https://t.co/0tnpyDj84W',
            'is_quote_status': True,
            'in_reply_to_status_id': None,
            'id': 877308619854934016,
            'favorite_count': 3,
            'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
            'quoted_status_id': 868579630294413312,
            'retweeted': False,
            'coordinates': None,
            'entities': {
                'symbols': [],
                'user_mentions': [{
                    'id': 314185571,
                    'indices': [32, 40],
                    'id_str': '314185571',
                    'screen_name': 'evl_uic',
                    'name': 'Electronic Vis. Lab'}],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/0tnpyDj84W',
                    'indices': [95, 118],
                    'expanded_url': 'https://twitter.com/i/web/status/877308619854934016',
                    'display_url': 'twitter.com/i/web/status/8\u2026'
                }]
            },
            'in_reply_to_screen_name': None,
            'in_reply_to_user_id': None,
            'retweet_count': 1,
            'id_str': '877308619854934016',
            'favorited': False,
            'geo': None,
            'in_reply_to_user_id_str': None,
            'possibly_sensitive': False,
            'lang': 'en',
            'created_at': 'Tue Jun 20 23:34:09 +0000 2017',
            'quoted_status_id_str': '868579630294413312',
            'in_reply_to_status_id_str': None,
            'place': None
        },
        'is_translation_enabled': False,
        'utc_offset': -18000,
        'statuses_count': 201,
        'description': 'The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
        'friends_count': 5,
        'location': 'Chicago, Il',
        'profile_link_color': 'B30000',
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
        'following': True,
        'geo_enabled': False,
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
        'name': 'Electronic Vis. Lab',
        'lang': 'en',
        'profile_background_tile': True,
        'favourites_count': 2,
        'screen_name': 'evl_uic',
        'notifications': False,
        'url': 'http://t.co/wLvtCCBQjl',
        'created_at': 'Thu Jun 09 21:07:18 +0000 2011',
        'contributors_enabled': False,
        'time_zone': 'Central Time (US & Canada)',
        'protected': False,
        'default_profile': False,
        'is_translator': False
    },
    time_zone='Central Time (US & Canada)',
    id=314185571,
    description='The Electronic Visualization Laboratory (EVL) is an interdisciplinary graduate research laboratory that combines art and computer science.',
    _api=<tweepy.api.API object at 0x101ed8f90>,
    verified=False,
    profile_location=None,
    profile_image_url_https='https://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
    profile_sidebar_fill_color='EFEFEF',
    is_translator=False,
    geo_enabled=False,
    entities={
        'url': {
            'urls': [{
                'url': 'http://t.co/wLvtCCBQjl',
                'indices': [0, 22],
                'expanded_url': 'http://www.evl.uic.edu/index2.php',
                'display_url': 'evl.uic.edu/index2.php'
            }]
        },
        'description': {'urls': []}
    },
    followers_count=375,
    protected=False,
    id_str='314185571',
    default_profile_image=False,
    listed_count=30,
    status=Status( #26 #source & source_url
        contributors=None,
        truncated=True,
        text='Looking forward to representing @evl_uic at the Brazilian Symposium on Collaborative Systems:\u2026 https://t.co/0tnpyDj84W',
        is_quote_status=True,
        in_reply_to_status_id=None,
        id=877308619854934016,
        favorite_count=3,
        _api=<tweepy.api.API object at 0x101ed8f90>,
        source='Twitter Web Client',
        quoted_status_id=868579630294413312,
        _json={ #25 #source includes source & source_url
            'contributors': None,
            'truncated': True,
            'text': 'Looking forward to representing @evl_uic at the Brazilian Symposium on Collaborative Systems:\u2026 https://t.co/0tnpyDj84W',
            'is_quote_status': True,
            'in_reply_to_status_id': None,
            'id': 877308619854934016,
            'favorite_count': 3,
            'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
            'quoted_status_id': 868579630294413312,
            'retweeted': False,
            'coordinates': None,
            'entities': {
                'symbols': [],
                'user_mentions': [{
                    'id': 314185571,
                    'indices': [32, 40],
                    'id_str': '314185571',
                    'screen_name': 'evl_uic',
                    'name': 'Electronic Vis. Lab'
                }],
                'hashtags': [],
                'urls': [{
                    'url': 'https://t.co/0tnpyDj84W',
                    'indices': [95, 118],
                    'expanded_url': 'https://twitter.com/i/web/status/877308619854934016',
                    'display_url': 'twitter.com/i/web/status/8\u2026'
                }]
            },
            'in_reply_to_screen_name': None,
            'in_reply_to_user_id': None,
            'retweet_count': 1,
            'id_str': '877308619854934016',
            'favorited': False,
            'geo': None,
            'in_reply_to_user_id_str': None,
            'possibly_sensitive': False,
            'lang': 'en',
            'created_at': 'Tue Jun 20 23:34:09 +0000 2017',
            'quoted_status_id_str': '868579630294413312',
            'in_reply_to_status_id_str': None,
            'place': None
        },
        coordinates=None,
        entities={
            'symbols': [],
            'user_mentions': [{
                'id': 314185571,
                'indices': [32, 40],
                'id_str': '314185571',
                'screen_name': 'evl_uic',
                'name': 'Electronic Vis. Lab'
            }],
            'hashtags': [],
            'urls': [{
                'url': 'https://t.co/0tnpyDj84W',
                'indices': [95, 118],
                'expanded_url': 'https://twitter.com/i/web/status/877308619854934016',
                'display_url': 'twitter.com/i/web/status/8\u2026'
            }]
        },
        in_reply_to_screen_name=None,
        id_str='877308619854934016',
        retweet_count=1,
        in_reply_to_user_id=None,
        favorited=False,
        source_url='http://twitter.com',
        geo=None,
        in_reply_to_user_id_str=None,
        possibly_sensitive=False,
        lang='en',
        created_at=datetime.datetime(2017, 6, 20, 23, 34, 9),
        quoted_status_id_str='868579630294413312',
        in_reply_to_status_id_str=None,
        place=None,
        retweeted=False
    ),
    lang='en',
    utc_offset=-18000,
    statuses_count=201,
    profile_background_color='131516',
    friends_count=5,
    profile_link_color='B30000',
    profile_image_url='http://pbs.twimg.com/profile_images/1531487079/evl-logo-only_normal.jpg',
    notifications=False,
    default_profile=False,
    favourites_count=2,
    profile_background_image_url_https='https://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_image_url='http://abs.twimg.com/images/themes/theme14/bg.gif',
    screen_name='evl_uic',
    is_translation_enabled=False,
    profile_background_tile=True,
    profile_text_color='B8B8B8',
    name='Electronic Vis. Lab',
    url='http://t.co/wLvtCCBQjl',
    created_at=datetime.datetime(2011, 6, 9, 21, 7, 18),
    contributors_enabled=False,
    location='Chicago, Il',
    profile_sidebar_border_color='EEEEEE',
    translator_type='none',
    following=True
)