Status(
    contributors=None,
    truncated=False,
    text='Maxine Brown @evl_uic @cinegridbr will be a keynote speaker at the 14\xba Brazilian Symposium on Collaborative Systems: https://t.co/cvH6i5pgOd',
    is_quote_status=False,
    in_reply_to_status_id=None,
    id=868579630294413312,
    favorite_count=2,
    _api=<tweepy.api.API object at 0x10cafff90>,
    author=User( #42
        follow_request_sent=False,
        has_extended_profile=False,
        profile_use_background_image=True,
        _json={ #42
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 24748438,
            'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': '333333',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'profile_sidebar_fill_color': 'DDFFCC',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/mVshlT4rB6',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.softwarestudies.com.br',
                        'display_url': 'softwarestudies.com.br'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 922,
            'profile_sidebar_border_color': 'BDDCAD',
            'id_str': '24748438',
            'profile_background_color': '9AE4E8',
            'listed_count': 60,
            'is_translation_enabled': False,
            'utc_offset': -10800,
            'statuses_count': 1125,
            'description': 'Software Studies Brazil @ Unifesp',
            'friends_count': 352,
            'location': 'S\xe3o Paulo, Brazil',
            'profile_link_color': '0084B4',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'following': False,
            'geo_enabled': False,
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
            'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'screen_name': 'softwarestudies',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 127,
            'name': 'Software Studies',
            'notifications': False,
            'url': 'http://t.co/mVshlT4rB6',
            'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
            'contributors_enabled': False,
            'time_zone': 'Brasilia',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        time_zone='Brasilia',
        id=24748438,
        description='Software Studies Brazil @ Unifesp',
        _api=<tweepy.api.API object at 0x10cafff90>,
        verified=False,
        profile_text_color='333333',
        profile_image_url_https='https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        profile_sidebar_fill_color='DDFFCC',
        is_translator=False,
        geo_enabled=False,
        entities={'url': {'urls': [{'url': 'http://t.co/mVshlT4rB6',
        'indices': [0,
        22],
        'expanded_url': 'http://www.softwarestudies.com.br',
        'display_url': 'softwarestudies.com.br'}]},
        'description': {'urls': []}},
        followers_count=922,
        protected=False,
        id_str='24748438',
        default_profile_image=False,
        listed_count=60,
        lang='en',
        utc_offset=-10800,
        statuses_count=1125,
        profile_background_color='9AE4E8',
        friends_count=352,
        profile_link_color='0084B4',
        profile_image_url='http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        notifications=False,
        default_profile=False,
        profile_background_image_url_https='https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        profile_banner_url='https://pbs.twimg.com/profile_banners/24748438/1400118299',
        profile_background_image_url='http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        name='Software Studies',
        is_translation_enabled=False,
        profile_background_tile=True,
        favourites_count=127,
        screen_name='softwarestudies',
        url='http://t.co/mVshlT4rB6',
        created_at=datetime.datetime(2009, 3, 16, 19, 15, 13),
        contributors_enabled=False,
        location='S\xe3o Paulo, Brazil',
        profile_sidebar_border_color='BDDCAD',
        translator_type='none',
        following=False
    ),
    _json={
        'contributors': None,
        'truncated': False,
        'text': 'Maxine Brown @evl_uic @cinegridbr will be a keynote speaker at the 14\xba Brazilian Symposium on Collaborative Systems: https://t.co/cvH6i5pgOd',
        'is_quote_status': False,
        'in_reply_to_status_id': None,
        'id': 868579630294413312,
        'favorite_count': 2,
        'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        'retweeted': False,
        'coordinates': None,
        'entities': {
            'symbols': [],
            'user_mentions': [
                {
                    'id': 314185571,
                    'indices': [13, 21],
                    'id_str': '314185571',
                    'screen_name': 'evl_uic',
                    'name': 'Electronic Vis. Lab'
                },
                {
                    'id': 2715769574,
                    'indices': [22,
                    33],
                    'id_str': '2715769574',
                    'screen_name': 'cinegridbr',
                    'name': 'CineGrid Brasil'
                }
            ],
            'hashtags': [],
            'urls': [{
                'url': 'https://t.co/cvH6i5pgOd',
                'indices': [117, 140],
                'expanded_url': 'http://csbc2017.mackenzie.br/eventos/14-sbsc',
                'display_url': 'csbc2017.mackenzie.br/eventos/14-sbsc'
            }]
        },
        'in_reply_to_screen_name': None,
        'in_reply_to_user_id': None,
        'retweet_count': 0,
        'id_str': '868579630294413312',
        'favorited': False,
        'user': { #42
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 24748438,
            'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': '333333',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'profile_sidebar_fill_color': 'DDFFCC',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/mVshlT4rB6',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.softwarestudies.com.br',
                        'display_url': 'softwarestudies.com.br'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 922,
            'profile_sidebar_border_color': 'BDDCAD',
            'id_str': '24748438',
            'profile_background_color': '9AE4E8',
            'listed_count': 60,
            'is_translation_enabled': False,
            'utc_offset': -10800,
            'statuses_count': 1125,
            'description': 'Software Studies Brazil @ Unifesp',
            'friends_count': 352,
            'location': 'S\xe3o Paulo, Brazil',
            'profile_link_color': '0084B4',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'following': False,
            'geo_enabled': False,
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
            'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'screen_name': 'softwarestudies',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 127,
            'name': 'Software Studies',
            'notifications': False,
            'url': 'http://t.co/mVshlT4rB6',
            'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
            'contributors_enabled': False,
            'time_zone': 'Brasilia',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        'geo': None,
        'in_reply_to_user_id_str': None,
        'possibly_sensitive': False,
        'possibly_sensitive_appealable': False,
        'lang': 'en',
        'created_at': 'Sat May 27 21:28:15 +0000 2017',
        'in_reply_to_status_id_str': None,
        'place': None
    },
    coordinates=None,
    entities={
        'symbols': [],
        'user_mentions': [
            {
                'id': 314185571,
                'indices': [13, 21],
                'id_str': '314185571',
                'screen_name': 'evl_uic',
                'name': 'Electronic Vis. Lab'
            },
            {
                'id': 2715769574,
                'indices': [22, 33],
                'id_str': '2715769574',
                'screen_name': 'cinegridbr',
                'name': 'CineGrid Brasil'
            }
        ],
        'hashtags': [],
        'urls': [{
            'url': 'https://t.co/cvH6i5pgOd',
            'indices': [117, 140],
            'expanded_url': 'http://csbc2017.mackenzie.br/eventos/14-sbsc',
            'display_url': 'csbc2017.mackenzie.br/eventos/14-sbsc'
        }]
    },
    in_reply_to_screen_name=None,
    id_str='868579630294413312',
    retweet_count=0,
    in_reply_to_user_id=None,
    favorited=False,
    source_url='http://twitter.com',
    user=User( #42
        follow_request_sent=False,
        has_extended_profile=False,
        profile_use_background_image=True,
        _json={ #42
            'follow_request_sent': False,
            'has_extended_profile': False,
            'profile_use_background_image': True,
            'default_profile_image': False,
            'id': 24748438,
            'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'verified': False,
            'translator_type': 'none',
            'profile_text_color': '333333',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'profile_sidebar_fill_color': 'DDFFCC',
            'entities': {
                'url': {
                    'urls': [{
                        'url': 'http://t.co/mVshlT4rB6',
                        'indices': [0, 22],
                        'expanded_url': 'http://www.softwarestudies.com.br',
                        'display_url': 'softwarestudies.com.br'
                    }]
                },
                'description': {'urls': []}
            },
            'followers_count': 922,
            'profile_sidebar_border_color': 'BDDCAD',
            'id_str': '24748438',
            'profile_background_color': '9AE4E8',
            'listed_count': 60,
            'is_translation_enabled': False,
            'utc_offset': -10800,
            'statuses_count': 1125,
            'description': 'Software Studies Brazil @ Unifesp',
            'friends_count': 352,
            'location': 'S\xe3o Paulo, Brazil',
            'profile_link_color': '0084B4',
            'profile_image_url': 'http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
            'following': False,
            'geo_enabled': False,
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24748438/1400118299',
            'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
            'screen_name': 'softwarestudies',
            'lang': 'en',
            'profile_background_tile': True,
            'favourites_count': 127,
            'name': 'Software Studies',
            'notifications': False,
            'url': 'http://t.co/mVshlT4rB6',
            'created_at': 'Mon Mar 16 19:15:13 +0000 2009',
            'contributors_enabled': False,
            'time_zone': 'Brasilia',
            'protected': False,
            'default_profile': False,
            'is_translator': False
        },
        time_zone='Brasilia',
        id=24748438,
        description='Software Studies Brazil @ Unifesp',
        _api=<tweepy.api.API object at 0x10cafff90>,
        verified=False,
        profile_text_color='333333',
        profile_image_url_https='https://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        profile_sidebar_fill_color='DDFFCC',
        is_translator=False,
        geo_enabled=False,
        entities={
            'url': {
                'urls': [{
                    'url': 'http://t.co/mVshlT4rB6',
                    'indices': [0, 22],
                    'expanded_url': 'http://www.softwarestudies.com.br',
                    'display_url': 'softwarestudies.com.br'
                }]
            },
            'description': {'urls': []}
        },
        followers_count=922,
        protected=False,
        id_str='24748438',
        default_profile_image=False,
        listed_count=60,
        lang='en',
        utc_offset=-10800,
        statuses_count=1125,
        profile_background_color='9AE4E8',
        friends_count=352,
        profile_link_color='0084B4',
        profile_image_url='http://pbs.twimg.com/profile_images/443089631/twitterProfilePhoto_normal.jpg',
        notifications=False,
        default_profile=False,
        profile_background_image_url_https='https://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        profile_banner_url='https://pbs.twimg.com/profile_banners/24748438/1400118299',
        profile_background_image_url='http://pbs.twimg.com/profile_background_images/5835147/sws-75px.jpg',
        name='Software Studies',
        is_translation_enabled=False,
        profile_background_tile=True,
        favourites_count=127,
        screen_name='softwarestudies',
        url='http://t.co/mVshlT4rB6',
        created_at=datetime.datetime(2009,
            3,
        16,
        19,
        15,
        13),
        contributors_enabled=False,
        location='S\xe3o Paulo, Brazil',
        profile_sidebar_border_color='BDDCAD',
        translator_type='none',
        following=False),
    geo=None,
    in_reply_to_user_id_str=None,
    possibly_sensitive=False,
    possibly_sensitive_appealable=False,
    lang='en',
    created_at=datetime.datetime(2017, 5, 27, 21, 28, 15),
    in_reply_to_status_id_str=None,
    place=None,
    source='Twitter Web Client',
    retweeted=False
)